/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/kevin/ros_ws/src/baxter_common/baxter_maintenance_msgs/srv/RMCores.srv
 *
 */


#ifndef BAXTER_MAINTENANCE_MSGS_MESSAGE_RMCORES_H
#define BAXTER_MAINTENANCE_MSGS_MESSAGE_RMCORES_H

#include <ros/service_traits.h>


#include <baxter_maintenance_msgs/RMCoresRequest.h>
#include <baxter_maintenance_msgs/RMCoresResponse.h>


namespace baxter_maintenance_msgs
{

struct RMCores
{

typedef RMCoresRequest Request;
typedef RMCoresResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RMCores
} // namespace baxter_maintenance_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_maintenance_msgs::RMCores > {
  static const char* value()
  {
    return "e357395786d5752c179252d49e6293b4";
  }

  static const char* value(const ::baxter_maintenance_msgs::RMCores&) { return value(); }
};

template<>
struct DataType< ::baxter_maintenance_msgs::RMCores > {
  static const char* value()
  {
    return "baxter_maintenance_msgs/RMCores";
  }

  static const char* value(const ::baxter_maintenance_msgs::RMCores&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_maintenance_msgs::RMCoresRequest> should match 
// service_traits::MD5Sum< ::baxter_maintenance_msgs::RMCores > 
template<>
struct MD5Sum< ::baxter_maintenance_msgs::RMCoresRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_maintenance_msgs::RMCores >::value();
  }
  static const char* value(const ::baxter_maintenance_msgs::RMCoresRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_maintenance_msgs::RMCoresRequest> should match 
// service_traits::DataType< ::baxter_maintenance_msgs::RMCores > 
template<>
struct DataType< ::baxter_maintenance_msgs::RMCoresRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_maintenance_msgs::RMCores >::value();
  }
  static const char* value(const ::baxter_maintenance_msgs::RMCoresRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_maintenance_msgs::RMCoresResponse> should match 
// service_traits::MD5Sum< ::baxter_maintenance_msgs::RMCores > 
template<>
struct MD5Sum< ::baxter_maintenance_msgs::RMCoresResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_maintenance_msgs::RMCores >::value();
  }
  static const char* value(const ::baxter_maintenance_msgs::RMCoresResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_maintenance_msgs::RMCoresResponse> should match 
// service_traits::DataType< ::baxter_maintenance_msgs::RMCores > 
template<>
struct DataType< ::baxter_maintenance_msgs::RMCoresResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_maintenance_msgs::RMCores >::value();
  }
  static const char* value(const ::baxter_maintenance_msgs::RMCoresResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MAINTENANCE_MSGS_MESSAGE_RMCORES_H
