"""autogenerated by genpy from baxter_core_msgs/ITBStates.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import baxter_core_msgs.msg

class ITBStates(genpy.Message):
  _md5sum = "5436edae8a7271b5fdefc6519f5ab8c3"
  _type = "baxter_core_msgs/ITBStates"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# used when publishing multiple itbs
string[]         names
ITBState[] states
================================================================================
MSG: baxter_core_msgs/ITBState
bool[4] buttons
bool    up
bool    down
bool    left
bool    right
uint8   wheel

# true if the inner light is on, false if not
bool innerLight

# true if the outer light is on, false if not
bool outerLight

"""
  __slots__ = ['names','states']
  _slot_types = ['string[]','baxter_core_msgs/ITBState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       names,states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ITBStates, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.names is None:
        self.names = []
      if self.states is None:
        self.states = []
    else:
      self.names = []
      self.states = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.names)
      buff.write(_struct_I.pack(length))
      for val1 in self.names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        buff.write(_struct_4B.pack(*val1.buttons))
        _x = val1
        buff.write(_struct_7B.pack(_x.up, _x.down, _x.left, _x.right, _x.wheel, _x.innerLight, _x.outerLight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.states is None:
        self.states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = baxter_core_msgs.msg.ITBState()
        start = end
        end += 4
        val1.buttons = _struct_4B.unpack(str[start:end])
        val1.buttons = map(bool, val1.buttons)
        _x = val1
        start = end
        end += 7
        (_x.up, _x.down, _x.left, _x.right, _x.wheel, _x.innerLight, _x.outerLight,) = _struct_7B.unpack(str[start:end])
        val1.up = bool(val1.up)
        val1.down = bool(val1.down)
        val1.left = bool(val1.left)
        val1.right = bool(val1.right)
        val1.innerLight = bool(val1.innerLight)
        val1.outerLight = bool(val1.outerLight)
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.names)
      buff.write(_struct_I.pack(length))
      for val1 in self.names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.states:
        buff.write(val1.buttons.tostring())
        _x = val1
        buff.write(_struct_7B.pack(_x.up, _x.down, _x.left, _x.right, _x.wheel, _x.innerLight, _x.outerLight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.states is None:
        self.states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.states = []
      for i in range(0, length):
        val1 = baxter_core_msgs.msg.ITBState()
        start = end
        end += 4
        val1.buttons = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=4)
        val1.buttons = map(bool, val1.buttons)
        _x = val1
        start = end
        end += 7
        (_x.up, _x.down, _x.left, _x.right, _x.wheel, _x.innerLight, _x.outerLight,) = _struct_7B.unpack(str[start:end])
        val1.up = bool(val1.up)
        val1.down = bool(val1.down)
        val1.left = bool(val1.left)
        val1.right = bool(val1.right)
        val1.innerLight = bool(val1.innerLight)
        val1.outerLight = bool(val1.outerLight)
        self.states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
_struct_7B = struct.Struct("<7B")
